apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slack
  namespace: argo-cd
spec:
  destination:
    namespace: slack
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    targetRevision: HEAD
    repoURL: 'https://github.com/slashr/homelab-deployments.git'
    path: src/slack
