apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slack-data
  namespace: slack
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
