registry_username: ENC[AES256_GCM,data:+769Ssc9,iv:7ucTxTUw/RfI5vZ19/W4PuSeD8C2auU+g2yXA/MnAMI=,tag:Un0PNwsL+kXaOoinVQKuHw==,type:str]
registry_password: ENC[AES256_GCM,data:JWgufdWAZWWXL0Elj1ZqDkPjRquj2Q==,iv:o8peqzExI1vG+EFZYRczzmpZYWlkYaSzwJj9JaeLZH4=,tag:3jaQFGbKd/u0Zk+9GheqXQ==,type:str]
sops:
    age:
        - recipient: age1p58f02kktcn4t0qrnnqf4jgx2z0xc9e60jxqffk2jxvcecgheylsp8g9qv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTeE8wQjNVWHpndU1QNGRq
            REhDQ0NGM2pXdnVFbkw1ZnV3YXdXb242U3prCnZBcWV3LzZvQ2JWK24rdUU4SWds
            aHRYNURkS1llMEJTREwweTZIVWdTRDgKLS0tIG4vK2ZRemEyM0hHS0pVaGwvSDZT
            U2Y4YlpNT2lTVm1KNENSUTBlc0svWlkKNtSN2eLOQX7bhNPkuhNasPkIJIwonBvz
            dL3vdUicb2a3JYUxXvIMkXjvaoxEEEfDA12oLLa0ibJuyjOsziWJpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T20:01:02Z"
    mac: ENC[AES256_GCM,data:dC+x9qTJWBggIvTWJfV82RSRUjPCMxzzKyzfc5oeKnVqAFiVrS7S58kFkZXR21CounjznSiMR7nC1SZpdZ1/GrCjkJSrwQEHkK6YS6aqKQcDugyW1sa+xpMrDyKQdrzRB2tnTxzASVJGm1eleudeDaCszva01O4nRdVrzbhx8Sw=,iv:1ttC1cOMBTNWI2RdaeghNxrezgvTNq1pNjag+TnMzTE=,tag:wKpYwbO/1mN9yZzlYRT6+g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
