apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argo-cd
  #finalizers:
  #- resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: podinfo
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    targetRevision: '>=6.*.*'
    repoURL: 'https://stefanprodan.github.io/podinfo'
    chart: podinfo
    helm:
      values: |
        replicaCount: '1'
        ui:
          color: "#37891e"
          logo: "https://c.tenor.com/KFWpTDMlfSsAAAAC/tenor.gif"
          message: "🌳🌲🌴🌵🥦"
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - host: "hey.shrub.dev"
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - hosts:
                - "hey.shrub.dev"
              secretName: podinfo-tls

          # Run a pod on each of the cluster Nodes
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                    - key: "name"
                      operator: In
                      values:
                        - "angela"
                        - "stanley"
                        - "phyllis"
                        - "toby"
