apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argo-cd
  #finalizers:
  #- resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: podinfo
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    targetRevision: '>=6.*.*'
    repoURL: 'https://stefanprodan.github.io/podinfo'
    chart: podinfo
    helm:
      values: |
        replicaCount: '1'
        ui:
          color: "#37891e"
          logo: "https://c.tenor.com/KFWpTDMlfSsAAAAC/tenor.gif"
          message: "🌳🌲🌴🌵🥦"
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                preference:
                  matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values:
                        - stanley-arm1
                    - key: kubernetes.io/os
                      operator: In
                      values:
                        - linux
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - host: "hey.shrub.dev"
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - hosts:
                - "hey.shrub.dev"
              secretName: podinfo-tls
