apiVersion: v1
kind: Service
metadata:
  name: adguard-ui-external
  namespace: adguard
  labels:
    app: adguard
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: adguard-ui-external
  namespace: adguard
  labels:
    app: adguard
subsets:
  - addresses:
      - ip: 100.100.1.102
    ports:
      - name: http
        port: 3000
        protocol: TCP
