apiVersion: v1
kind: Service
metadata:
  name: adguard-ui-external
  namespace: adguard
  labels:
    app: adguard
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: adguard-ui-external
  namespace: adguard
  labels:
    app: adguard
    kubernetes.io/service-name: adguard-ui-external
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 3000
endpoints:
  - addresses:
      - 100.100.1.102
