apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz-k8s-infra
  namespace: argo-cd
spec:
  destination:
    namespace: signoz
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    targetRevision: '>=0.13.0'
    repoURL: 'https://charts.signoz.io'
    chart: k8s-infra
    helm:
      values: |
        clusterName: shrub-dev
        otelCollectorEndpoint: signoz-otel-collector.signoz.svc.cluster.local:4317
        otelInsecure: true
        otelAgent: {}
        otelDeployment:
          nodeSelector:
            kubernetes.io/hostname: stanley-arm1
            kubernetes.io/os: linux
