apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: kernel-mode
spec:
  statefulSet:
    pod:
      tailscaleContainer:
        env:
          - name: TS_USERSPACE
            value: "false"
