apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webtop-data
  namespace: webtop
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
