apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: webtop
  namespace: webtop
spec:
  serviceName: webtop
  replicas: 1
  selector:
    matchLabels: { app: webtop }
  template:
    metadata:
      labels: { app: webtop }
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 1.1.1.1
        searches:
          - webtop.svc.cluster.local
          - svc.cluster.local
          - cluster.local
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - stanley-arm1
                      - phyllis-arm2
      initContainers:
        - name: setup-scripts
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              mkdir -p /config/custom-cont-init.d
              cp /scripts/* /config/custom-cont-init.d/
              chmod +x /config/custom-cont-init.d/*
          volumeMounts:
            - name: webtop-data
              mountPath: /config
            - name: custom-scripts
              mountPath: /scripts
      containers:
        - name: webtop
          image: lscr.io/linuxserver/webtop:latest
          securityContext:
            seccompProfile:
              type: Unconfined
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/bash
                  - -c
                  - |
                    sleep 30 && /config/custom-cont-init.d/setup-mouse-jiggler.sh &
          ports:
            - name: web
              containerPort: 3000
              protocol: TCP
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Amsterdam"
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "3Gi"
          volumeMounts:
            - name: webtop-data
              mountPath: /config
            - name: dshm
              mountPath: /dev/shm
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 2Gi
        - name: tmp
          emptyDir:
            medium: Memory
            sizeLimit: 512Mi
        - name: custom-scripts
          configMap:
            name: webtop-scripts
            defaultMode: 0755
  volumeClaimTemplates:
    - metadata:
        name: webtop-data
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: local-path
        resources:
          requests:
            storage: 5Gi
