apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: webtop
  namespace: webtop
spec:
  serviceName: webtop
  replicas: 1
  selector:
    matchLabels: { app: webtop }
  template:
    metadata:
      labels: { app: webtop }
      annotations:
        # Velero pre-backup hook: flush filesystem and gracefully signal Chromium to save
        backup.velero.io/backup-volumes: webtop-data
        pre.hook.backup.velero.io/command: '["/bin/sh", "-c", "pkill -SIGUSR1 chromium 2>/dev/null; sync"]'
        pre.hook.backup.velero.io/timeout: "30s"
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.43.0.10
          - 8.8.8.8
          - 1.1.1.1
        searches:
          - webtop.svc.cluster.local
          - svc.cluster.local
          - cluster.local
      nodeSelector:
        kubernetes.io/hostname: jim-pi
      containers:
        # HTTP -> HTTPS proxy sidecar for Tailscale ingress compatibility
        - name: proxy
          image: nginx:alpine
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
        - name: webtop
          image: kasmweb/debian-trixie-desktop:1.18.0
          securityContext:
            privileged: true
          ports:
            - name: web
              containerPort: 6901
              protocol: TCP
          env:
            - name: VNC_PW
              value: "attribute"
          resources:
            requests:
              memory: "1500Mi"
              cpu: "2"
            limits:
              memory: "4Gi"
              cpu: "3"
          readinessProbe:
            tcpSocket:
              port: 6901
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 6901
            initialDelaySeconds: 60
            periodSeconds: 30
          volumeMounts:
            - name: webtop-data
              mountPath: /config
            - name: dshm
              mountPath: /dev/shm
            - name: tmp
              mountPath: /tmp
            - name: custom-startup
              mountPath: /dockerstartup/custom_startup.sh
              subPath: custom_startup.sh
            - name: kasmvnc-config
              mountPath: /usr/share/kasmvnc/kasmvnc_defaults.yaml
              subPath: kasmvnc_defaults.yaml
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
        - name: tmp
          emptyDir:
            medium: Memory
            sizeLimit: 256Mi
        - name: custom-startup
          configMap:
            name: webtop-scripts
            defaultMode: 0755
            items:
              - key: custom_startup.sh
                path: custom_startup.sh
        - name: kasmvnc-config
          configMap:
            name: webtop-scripts
            items:
              - key: kasmvnc_defaults.yaml
                path: kasmvnc_defaults.yaml
        - name: nginx-config
          configMap:
            name: webtop-scripts
            items:
              - key: nginx.conf
                path: default.conf
  volumeClaimTemplates:
    - metadata:
        name: webtop-data
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: local-path
        resources:
          requests:
            storage: 5Gi
