apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: webtop
  namespace: webtop
spec:
  serviceName: webtop
  replicas: 1
  selector:
    matchLabels: { app: webtop }
  template:
    metadata:
      labels: { app: webtop }
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - stanley-arm1
                      - phyllis-arm2
      containers:
        - name: webtop
          image: lscr.io/linuxserver/webtop:latest
          ports:
            - name: web
              containerPort: 3000
              protocol: TCP
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Amsterdam"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1536Mi"
              cpu: "2000m"
          volumeMounts:
            - name: webtop-data
              mountPath: /config
  volumeClaimTemplates:
    - metadata:
        name: webtop-data
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: local-path
        resources:
          requests:
            storage: 5Gi
