apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: webtop
  namespace: webtop
spec:
  serviceName: webtop
  replicas: 1
  selector:
    matchLabels: { app: webtop }
  template:
    metadata:
      labels: { app: webtop }
      annotations:
        backup.velero.io/backup-volumes: webtop-data
        pre.hook.backup.velero.io/command: '["/bin/sh", "-c", "pkill -SIGUSR1 chromium 2>/dev/null; sync"]'
        pre.hook.backup.velero.io/timeout: "30s"
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.43.0.10
          - 8.8.8.8
          - 1.1.1.1
        searches:
          - webtop.svc.cluster.local
          - svc.cluster.local
          - cluster.local
      nodeSelector:
        kubernetes.io/hostname: jim-pi
      initContainers:
        - name: setup-scripts
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              set -e
              mkdir -p /config/custom-cont-init.d
              cp /scripts-init/* /config/custom-cont-init.d/
              chmod +x /config/custom-cont-init.d/*
          volumeMounts:
            - name: webtop-data
              mountPath: /config
            - name: init-scripts
              mountPath: /scripts-init
      containers:
        - name: webtop
          image: lscr.io/linuxserver/webtop:latest
          securityContext:
            privileged: true
          ports:
            - name: web
              containerPort: 3000
              protocol: TCP
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: webtop-scripts
                  key: TIMEZONE
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "3Gi"
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 30
          volumeMounts:
            - name: webtop-data
              mountPath: /config
            - name: dshm
              mountPath: /dev/shm
            - name: tmp
              mountPath: /tmp
            - name: dri
              mountPath: /dev/dri
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 2Gi
        - name: tmp
          emptyDir:
            medium: Memory
            sizeLimit: 512Mi
        - name: dri
          hostPath:
            path: /dev/dri
            type: Directory
        - name: init-scripts
          configMap:
            name: webtop-scripts
            defaultMode: 0755
            items:
              - key: init-cron.sh
                path: init-cron.sh
        - name: scripts
          configMap:
            name: webtop-scripts
            defaultMode: 0755
            items:
              - key: mmover.sh
                path: mmover.sh
              - key: ff-o.sh
                path: ff-o.sh
              - key: ff-c.sh
                path: ff-c.sh
              - key: workday-keeper.sh
                path: workday-keeper.sh
  volumeClaimTemplates:
    - metadata:
        name: webtop-data
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: local-path
        resources:
          requests:
            storage: 5Gi
