apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz
  namespace: argo-cd
spec:
  destination:
    namespace: signoz
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    targetRevision: '>=0.84.0'
    repoURL: 'https://charts.signoz.io'
    chart: signoz
    helm:
      values: |
        signoz:
          ingress:
            enabled: true
            className: "traefik"
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - host: signoz.shrub.dev
                paths:
                  - path: /
                    pathType: ImplementationSpecific
                    port: 8080
            tls:
              - hosts:
                  - signoz.shrub.dev
                secretName: signoz-tls

          otelCollector:
            config:
              receivers:
                hostmetrics:
                  collection_interval: 60s
                  scrapers:
                    cpu:
                    memory:
                    filesystem:
                    network:
              service:
                pipelines:
                  metrics:
                    receivers: [otlp, hostmetrics]
                    processors: [batch]
                    exporters: [clickhousemetricswrite, metadataexporter, signozclickhousemetrics]
        clickhouse:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - jim-pi
                          - michael-pi


