apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz
  namespace: argo-cd
spec:
  destination:
    namespace: signoz
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
    - SkipDryRunOnMissingResource=true
    - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: clickhouse.altinity.com
      kind: ClickHouseInstallation
      jsonPointers:
        - /spec/templates/podTemplates
  project: default
  source:
    targetRevision: '>=0.84.0'
    repoURL: 'https://charts.signoz.io'
    chart: signoz
    helm:
      values: |
        signoz:
          ingress:
            enabled: true
            className: "traefik"
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - host: signoz.shrub.dev
                paths:
                  - path: /
                    pathType: ImplementationSpecific
                    port: 8080
            tls:
              - hosts:
                  - signoz.shrub.dev
                secretName: signoz-tls

          # Pin SigNoz query service to stanley-arm1
          queryService:
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: kubernetes.io/hostname
                          operator: In
                          values:
                            - stanley-arm1

          otelCollector:
            # Pin central collector to stanley-arm1
            nodeSelector:
              kubernetes.io/hostname: stanley-arm1
              kubernetes.io/os: linux
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: kubernetes.io/hostname
                          operator: In
                          values:
                            - stanley-arm1
            config:
              receivers:
                hostmetrics:
                  collection_interval: 60s
                  scrapers:
                    cpu:
                    memory:
                    filesystem:
                    network:
              service:
                pipelines:
                  metrics:
                    receivers: [otlp, hostmetrics]
                    processors: [batch]
                    exporters: [clickhousemetricswrite, metadataexporter, signozclickhousemetrics]

        # Disable schema migrator sync hook temporarily
        schemaMigrator:
          enabled: false

        clickhouse:
          # Fix musl libc DNS resolution issue with ndots:5
          dnsConfig:
            options:
              - name: ndots
                value: "2"
          initContainers:
            udf:
              image:
                registry: docker.io
                repository: busybox
                tag: "1.36"
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - stanley-arm1
          persistence:
            size: 30Gi
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              memory: 4Gi
          # Pin Zookeeper to stanley-arm1
          zookeeper:
            nodeSelector:
              kubernetes.io/hostname: stanley-arm1
              kubernetes.io/os: linux
            persistence:
              size: 2Gi
          # System table TTL - keep internal ClickHouse logs for 3 days
          clickhouseOperator:
            nodeSelector:
              kubernetes.io/hostname: stanley-arm1
              kubernetes.io/os: linux
            queryLog:
              ttl: 3
            partLog:
              ttl: 3
            traceLog:
              ttl: 3
            metricLog:
              ttl: 3
            asynchronousMetricLog:
              ttl: 3
            processorsProfileLog:
              ttl: 3

        # Retention settings - keep logs/traces for 7 days, metrics for 30 days
        queryService:
          configVars:
            storage:
              logs:
                ttl_duration_hrs: 168  # 7 days
              traces:
                ttl_duration_hrs: 168  # 7 days
              metrics:
                ttl_duration_hrs: 720  # 30 days
