apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz
  namespace: argo-cd
spec:
  destination:
    namespace: signoz
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
    - SkipDryRunOnMissingResource=true
    - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: clickhouse.altinity.com
      kind: ClickHouseInstallation
      jsonPointers:
        - /spec/templates/podTemplates
  project: default
  source:
    targetRevision: '>=0.84.0'
    repoURL: 'https://charts.signoz.io'
    chart: signoz
    helm:
      values: |
        signoz:
          ingress:
            enabled: true
            className: "traefik"
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - host: signoz.shrub.dev
                paths:
                  - path: /
                    pathType: ImplementationSpecific
                    port: 8080
            tls:
              - hosts:
                  - signoz.shrub.dev
                secretName: signoz-tls

          # Pin SigNoz query service to stanley-arm1
          queryService:
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: kubernetes.io/hostname
                          operator: In
                          values:
                            - stanley-arm1

          otelCollector:
            # Pin central collector to stanley-arm1
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: kubernetes.io/hostname
                          operator: In
                          values:
                            - stanley-arm1
            config:
              receivers:
                hostmetrics:
                  collection_interval: 60s
                  scrapers:
                    cpu:
                    memory:
                    filesystem:
                    network:
              service:
                pipelines:
                  metrics:
                    receivers: [otlp, hostmetrics]
                    processors: [batch]
                    exporters: [clickhousemetricswrite, metadataexporter, signozclickhousemetrics]

        # Disable schema migrator sync hook temporarily
        schemaMigrator:
          enabled: false

        clickhouse:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - stanley-arm1
          persistence:
            size: 30Gi
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 2000m
              memory: 4Gi
          # Note: System table TTL is set to 30 days by chart default.
          # To reduce to 3 days, run manually after pod creation:
          # ALTER TABLE system.query_log MODIFY TTL event_date + INTERVAL 3 DAY;
          # (see signoz troubleshooting docs for full list)
          # Zookeeper runs on jim-pi (chart doesn't expose affinity settings)
          zookeeper:
            persistence:
              size: 2Gi

        # Retention settings - keep logs/traces for 7 days, metrics for 30 days
        queryService:
          configVars:
            storage:
              logs:
                ttl_duration_hrs: 168  # 7 days
              traces:
                ttl_duration_hrs: 168  # 7 days
              metrics:
                ttl_duration_hrs: 720  # 30 days
