apiVersion: v1
kind: Service
metadata:
  name: signoz-otel-collector-tailnet
  namespace: signoz
  annotations:
    argocd.argoproj.io/tracking-id: signoz-collector-nodeport:/Service:signoz/signoz-otel-collector-tailnet
  labels:
    app.kubernetes.io/component: otel-collector-tailnet
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/name: signoz
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/component: otel-collector
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/name: signoz
  ports:
    - name: otlp
      port: 4317
      protocol: TCP
      targetPort: otlp
      nodePort: 31317
