apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kash-data
  namespace: kash
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
