apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actualbudget-data
  namespace: actualbudget
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
